project_name: kube-slowwhy

before:
  hooks:
    - go mod tidy
    - go test ./...

builds:
  - main: ./cmd/kube-slowwhy
    binary: kube-slowwhy
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.ShortCommit}}
      - -X main.date={{.Date}}

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: checksums.txt
  algorithm: sha256

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^chore:"
      - "^ci:"
      - "^test:"

brews:
  - repository:
      owner: marek-kar
      name: homebrew-tap
    homepage: https://github.com/marek-kar/kube-slowwhy
    description: Fast, read-only root cause analysis for slow Kubernetes clusters
    license: MIT
    install: |
      bin.install "kube-slowwhy"
